# Generated by Django 5.2 on 2025-04-23 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('qr', 'Pago con QR'), ('efectivo', 'Pago en Efectivo (contra entrega)'), ('tigo_money', 'Tigo Money')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('token_transaccion', models.CharField(blank=True, max_length=255, null=True)),
                ('id_transaccion', models.CharField(blank=True, max_length=255, null=True)),
                ('datos_adicionales', models.JSONField(blank=True, null=True)),
                ('qr_imagen', models.ImageField(blank=True, null=True, upload_to='pagos/qr/', verbose_name='Imagen QR de pago')),
                ('qr_instrucciones', models.TextField(blank=True, null=True, verbose_name='Instrucciones para pago QR')),
                ('api_callback_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL de callback de API')),
                ('api_webhook_recibido', models.BooleanField(default=False, verbose_name='Webhook recibido')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
