# Generated by Django 5.2 on 2025-04-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_qrpredefinido'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientopedido',
            name='whatsapp_notification_url',
            field=models.URLField(blank=True, help_text='URL generada para enviar notificación por WhatsApp', null=True, verbose_name='URL de notificación WhatsApp'),
        ),
        migrations.AddField(
            model_name='seguimientopedido',
            name='whatsapp_sent',
            field=models.BooleanField(default=False, help_text='Indica si la notificación por WhatsApp fue enviada', verbose_name='Notificación WhatsApp enviada'),
        ),
    ]
