# Generated by Django 5.2 on 2025-05-07 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_seguimientopedido_whatsapp_notification_url_and_more'),
        ('productos', '0005_product_is_active_alter_product_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_llegada_estimada', models.DateField(blank=True, help_text='Fecha estimada de llegada del producto', null=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('anticipo', models.DecimalField(blank=True, decimal_places=2, help_text='Monto pagado como anticipo', max_digits=10, null=True)),
                ('fecha_anticipo', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('confirmada', 'Confirmada'), ('pagada', 'Pagada parcialmente'), ('lista', 'Lista para entrega'), ('convertida', 'Convertida a pedido'), ('cancelada', 'Cancelada')], default='solicitada', max_length=20)),
                ('notas_cliente', models.TextField(blank=True, help_text='Notas adicionales del cliente sobre la reserva', null=True)),
                ('notas_admin', models.TextField(blank=True, help_text='Notas internas para administradores', null=True)),
                ('notificacion_enviada', models.BooleanField(default=False, help_text='Indica si se ha enviado notificación cuando el producto está disponible')),
                ('pedido_creado', models.ForeignKey(blank=True, help_text='Pedido generado a partir de esta reserva', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='productos.product')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
