# Generated by Django 5.2 on 2025-05-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='comprobante_anticipo',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/anticipos/'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_limite_anticipo',
            field=models.DateTimeField(blank=True, help_text='Fecha límite para realizar el anticipo', null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='porcentaje_anticipo',
            field=models.DecimalField(decimal_places=2, default=30, help_text='Porcentaje requerido como anticipo', max_digits=5),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('solicitada', 'Solicitada'), ('confirmada', 'Confirmada'), ('anticipo_pendiente', 'Anticipo Pendiente'), ('pagada', 'Pagada parcialmente'), ('lista', 'Lista para entrega'), ('convertida', 'Convertida a pedido'), ('cancelada', 'Cancelada')], default='solicitada', max_length=20),
        ),
    ]
