# Generated by Django 5.2 on 2025-05-08 19:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_reserva_comprobante_anticipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('confirmada', 'Confirmada'), ('anticipo_pendiente', 'Anticipo Pendiente'), ('pagada', 'Pagada parcialmente'), ('lista', 'Lista para entrega'), ('convertida', 'Convertida a pedido'), ('cancelada', 'Cancelada')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('whatsapp_notification_url', models.URLField(blank=True, help_text='URL generada para enviar notificación por WhatsApp', null=True, verbose_name='URL de notificación WhatsApp')),
                ('whatsapp_sent', models.BooleanField(default=False, help_text='Indica si la notificación por WhatsApp fue enviada', verbose_name='Notificación WhatsApp enviada')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='pedidos.reserva')),
            ],
            options={
                'verbose_name': 'Seguimiento de reserva',
                'verbose_name_plural': 'Seguimientos de reservas',
                'ordering': ['-fecha'],
            },
        ),
    ]
