# Generated by Django 5.2 on 2025-04-30 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(blank=True, max_length=20, verbose_name='Cédula de Identidad')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Número de teléfono')),
                ('ciudad_residencia', models.CharField(blank=True, max_length=100, verbose_name='Ciudad de residencia')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección completa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
