# Generated by Django 5.2 on 2025-04-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_category_image_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home_image',
            field=models.ImageField(blank=True, help_text='Imagen específica para mostrar en la página de inicio. Si no se proporciona, se usará la imagen principal.', null=True, upload_to='categories/home/', verbose_name='Imagen para página de inicio'),
        ),
    ]
