# Generated by Django 5.2 on 2025-05-07 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_product_is_active_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_reservable',
            field=models.BooleanField(default=False, help_text='Indica si este producto puede ser reservado', verbose_name='Disponible para reserva'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_reservation_days',
            field=models.PositiveIntegerField(default=3, help_text='Tiempo mínimo en días requerido para la reserva', verbose_name='Días mínimos de reserva'),
        ),
    ]
